<?php

/**
 * LUM_PollRoleBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_PollRoleBlockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_PollRoleBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_PollRoleBlock');
    }
}