<?php

/**
 * LUM_ReleasesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_ReleasesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_ReleasesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Releases');
    }
}