<?php

/**
 * LUM_DiscussionUserWhisperToTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_DiscussionUserWhisperToTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_DiscussionUserWhisperToTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_DiscussionUserWhisperTo');
    }
}