<?php

/**
 * LUM_UserFieldPermsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_UserFieldPermsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_UserFieldPermsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_UserFieldPerms');
    }
}