<?php

/**
 * OuiedireMailingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OuiedireMailingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OuiedireMailingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OuiedireMailing');
    }
}