<?php

/**
 * WpCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpCategories');
    }
}