<?php

/**
 * WpCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpComments');
    }
}