<?php

/**
 * WpOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpOptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpOptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpOptions');
    }
}