<?php

/**
 * WpPost2tagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpPost2tagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpPost2tagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpPost2tag');
    }
}