<?php

/**
 * WpPost2catTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpPost2catTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpPost2catTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpPost2cat');
    }
}