<?php

/**
 * WpPostsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpPostsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpPostsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpPosts');
    }
}