<?php

/**
 * WpTagSynonymsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpTagSynonymsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpTagSynonymsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpTagSynonyms');
    }
}