<?php

/**
 * WpTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpTags');
    }
}