<?php

/**
 * WpUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WpUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WpUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WpUsers');
    }
}