<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addlumuserbookmark extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('LUM_UserBookmark', array(
             'userid' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'discussionid' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'userid',
              1 => 'discussionid',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('LUM_UserBookmark');
    }
}