<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addwpoptions extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('wp_options', array(
             'option_id' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'blog_id' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'option_name' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => false,
              'length' => 64,
             ),
             'option_can_override' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'Y',
              1 => 'N',
              ),
              'primary' => false,
              'default' => 'Y',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'option_type' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '1',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'option_value' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'option_width' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '20',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'option_height' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '8',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'option_description' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'option_admin_level' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '1',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'autoload' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'yes',
              1 => 'no',
              ),
              'primary' => false,
              'default' => 'yes',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 3,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'option_id',
              1 => 'blog_id',
              2 => 'option_name',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('wp_options');
    }
}