<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addwplinkcategories extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('wp_linkcategories', array(
             'cat_id' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'cat_name' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'auto_toggle' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'Y',
              1 => 'N',
              ),
              'primary' => false,
              'default' => 'N',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'show_images' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'Y',
              1 => 'N',
              ),
              'primary' => false,
              'default' => 'Y',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'show_description' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'Y',
              1 => 'N',
              ),
              'primary' => false,
              'default' => 'N',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'show_rating' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'Y',
              1 => 'N',
              ),
              'primary' => false,
              'default' => 'Y',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'show_updated' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'Y',
              1 => 'N',
              ),
              'primary' => false,
              'default' => 'Y',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'sort_order' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => 'rand',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 64,
             ),
             'sort_desc' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'Y',
              1 => 'N',
              ),
              'primary' => false,
              'default' => 'N',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'text_before_link' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '<li>',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 128,
             ),
             'text_after_link' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '<br />',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 128,
             ),
             'text_after_all' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '</li>',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 128,
             ),
             'list_limit' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '-1',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'cat_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('wp_linkcategories');
    }
}