generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LUM_Zeitgeist
    theme:                 twitter
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lum_zeitgeist
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        dateend:     {label: "Date de fin", help: "Jour clôturant la période couverte par le numéro"}
        datestart:   {label: "Date de début", help: "Jour débutant la période couverte par le numéro"}
        description: {label: "Présentation du numéro", help: "Éventuel texte de présentation du numéro"}
        image:       {label: "L'image de la semaine", help: "URL vers l'image de la semaine"}
        ispublished: {label: "Publié ?", help: "L'épisode est-il visible en ligne ?"}
        zeitgeistid: {label: "Numéro", help: "Numéro de l'épisode"}
      list:
        title: Les Zeitgeists
        display: [=zeitgeistid, ispublished, datestart, dateend, _mixes_count, _releases_count, _events_count, _users_count]
      filter:  ~
      form:    ~
      edit:
        title: "Modifier le Zeitgeist #%%zeitgeistid%%"
        display:
          'Période couverte': [datestart, dateend]
          'Textes': [description]
          'Nouveautés': [_newstuff]
          'À venir': []
      new:
        title: "Créer un Zeitgeist"

